/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"


void
add_prog_1(char *host,int x,int y,int opcao)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;
	int  *result_2;
	numbers  sub_1_arg;
	int  *result_3;
	numbers  mult_1_arg;
	int  *result_4;
	numbers  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a=x;
	add_1_arg.b =y;
	switch(opcao){
	case 1:	
	
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Resutlado da soma: %d\n",*result_1);
	}
	break;

	case 2:
	result_2 = sub_1(&add_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("Resultado da subtração : %d\n",*result_2);
	}
	break;

	case 3:
	result_3 = mult_1(&add_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("Resultado da Multiplicação : %d\n",*result_3);
	}
	break;

	case 4:
	result_4 = div_1(&add_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
	printf("Resultado da divisão : %d\n",*result_4);
	}
	break;
	default:
	printf("Opção Invalida!\n");
	break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int x,y,opcao;
	if (argc < 4) {
		printf ("usage: %s <servidor> <numero1> <numero2>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	x=atoi(argv[2]);
	y=atoi(argv[3]);

	printf("Escolha uma operação:\n 1-Soma\n2-Subtração\n3-Multiplicação\n4-Divisao\nDigite a sua opção:");
	scanf("%d",&opcao);
	add_prog_1(host,x,y,opcao);
exit (0);
}
